### ISSUE TITLE
Adding Note button doesn't work

### ISSUE THREAD

**Issue by lilwalta** [dcode-youtube/notes-app-javascript-localstorage#2]
When writing all the code following to tutorial to understand JS a bit more (thanks so much btw) I found that my app didn't work quite right. I ended up coming here and downloading the source code but it didn't work either. The "Adding Note" button doesn't do anything and clicking on the note doesn't do anything either.

**Comment by kuacci** [comment]
Have you checked the event listener for the Add Note button? Also, the handler in app.js.

**Comment by lilwalta** [comment]
I actually just fixed it in one of my repos, I had to move all the js to one file and remove some of it.
